### ISSUE TITLE
--eval mAP error

### ISSUE THREAD

**Issue by Adlith** [open-mmlab/mmrotate#10] opened 2022-02-19 06:48 UTC
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
python ./tools/test.py \            
  configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_1x_dota_le90.py \
  rotated_retinanet_obb_r50_fpn_1x_dota_le90-c0097bc4.pth --eval mAP     
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
```
fatal: not a git repository (or any of the parent directories): .git
sys.platform: linux
Python: 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.2.r11.2/compiler.29618528_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.10.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1+cu113
OpenCV: 4.5.4
MMCV: 1.4.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMRotate: 0.1.0+
```

**Error traceback**
If applicable, paste the error trackback here.

```none
load checkpoint from local path: rotated_retinanet_obb_r50_fpn_1x_dota_le90-c0097bc4.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 10833/10833, 18.6 task/s, elapsed: 584s, ETA:     0sTraceback (most recent call last):
  File "./tools/test.py", line 238, in <module>
    main()
  File "./tools/test.py", line 230, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/home/featurize/mmrotate/mmrotate/datasets/dota.py", line 202, in evaluate
    logger=logger)
  File "/home/featurize/mmrotate/mmrotate/datasets/dota.py", line 375, in eval_map
    det_results, annotations, i)
  File "/home/featurize/mmrotate/mmrotate/datasets/dota.py", line 613, in get_cls_results
    cls_gts.append(ann['bboxes'][gt_inds, :])
TypeError: list indices must be integers or slices, not tuple
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by zytx121** [comment] 2022-02-19 08:04
Sorry, I will check it.

**Comment by zytx121** [comment] 2022-02-19 08:21
This problem is caused by the fact that we do not have the true value of the DOTA test set. You can change the test path in the configuration file to the val set or trainval set for the offline evalution.

I guess this problem is due to our document error. We will modify it immediately.

**Comment by Adlith** [comment] 2022-02-19 08:40
This repo is a great work, thank you for sharing it

**Comment by Adlith** [comment] 2022-02-19 08:51
after I change my test path to val set, new error appears:
![image](https://user-images.githubusercontent.com/13307223/154793910-a70a598f-70bd-40a2-a1fd-8dbcea0a3bec.png)
```
 load checkpoint from local path: rotated_retinanet_obb_r50_fpn_1x_dota_le90-c0097bc4.pth
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "./tools/test.py", line 238, in <module>
    main()
  File "./tools/test.py", line 230, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/home/featurize/mmrotate/mmrotate/datasets/dota.py", line 202, in evaluate
    logger=logger)
  File "/home/featurize/mmrotate/mmrotate/datasets/dota.py", line 366, in eval_map
    num_classes = len(det_results[0])  # positive class num
IndexError: list index out of range
```

**Comment by zytx121** [comment] 2022-02-19 09:04
Thank you for your issues, too.

**Comment by Adlith** [comment] 2022-02-19 11:31
After I change the test path in the configuration file to the val set, the program just stuck as shown in the image.
Can you teach me to solve it?
![image](https://user-images.githubusercontent.com/13307223/154798923-1a5d5df9-79c3-49d2-bd01-c771fcd50c41.png)

**Comment by zytx121** [comment] 2022-02-20 05:57
You can try:
```shell
python ./tools/test.py \
  configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
  checkpoints/SOME_CHECKPOINT.pth --eval mAP
```
or
```shell
python ./tools/test.py  \
  configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
  checkpoints/SOME_CHECKPOINT.pth  --format-only \
  --eval-options submission_dir=work_dirs/Task1_results
```

**Comment by Adlith** [comment] 2022-02-20 06:11
> You can try:
> 
> ```shell
> python ./tools/test.py \
>   configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
>   checkpoints/SOME_CHECKPOINT.pth --eval mAP
> ```
> 
> or
> 
> ```shell
> python ./tools/test.py  \
>   configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
>   checkpoints/SOME_CHECKPOINT.pth  --format-only \
>   --eval-options submission_dir=work_dirs/Task1_results
> ```
sorry，it also stucks.
![image](https://user-images.githubusercontent.com/13307223/154830902-cd307ac9-237d-46d8-93ba-c96069e7832a.png)

**Comment by zytx121** [comment] 2022-02-20 06:38
Can you describe how you get the val set data? And what is the TXT format?

**Comment by Adlith** [comment] 2022-02-20 06:42
I use the below command to get val set:
```
python tools/data/dota/split/img_split.py --base_json tools/data/dota/split/split_configs/dota1_0/ss_val.json
```
and the format of TXT is shown in the screen shot:
![image](https://user-images.githubusercontent.com/13307223/154831734-ce2b933f-02ce-4f8b-9405-de7b26e5245f.png)
![image](https://user-images.githubusercontent.com/13307223/154831749-6250bec9-e7f1-45e9-bb2c-3f60440a541d.png)

**Comment by zytx121** [comment] 2022-02-20 07:06
OK, your val set is right. Please try:
```shell
./tools/dist_test.sh \
configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
checkpoints/SOME_CHECKPOINT.pth 1 --eval mAP
```
and
```shell
./tools/dist_test.sh \
configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
  checkpoints/SOME_CHECKPOINT.pth  1 --format-only \
  --eval-options submission_dir=work_dirs/Task1_results
```

**Comment by liuyanyi** [comment] 2022-02-20 07:12
I also stuck at result formating, i modify the merge_det func in dota.py from [OBBDetection](https://github.com/jbwang1997/OBBDetection/blob/master/mmdet/datasets/obb/dota.py) and set to single process, it works fine.

**Comment by zytx121** [comment] 2022-02-20 07:19
> I also stuck at result formating, i modify the merge_det func in dota.py from [OBBDetection](https://github.com/jbwang1997/OBBDetection/blob/master/mmdet/datasets/obb/dota.py) and set to single process, it works fine.

Thank you for locating the bug. We'll fix it as soon as possible.

**Comment by zytx121** [comment] 2022-02-20 07:26
@Adlith You can fix the bug by changing 4 to 1. https://github.com/open-mmlab/mmrotate/blob/6519a3654e17b707c15d4aa2c5db1257587ea4c0/mmrotate/datasets/dota.py#L242

We'll  PR later.

**Comment by Adlith** [comment] 2022-02-20 07:48
The command below work well but only changing ```min(4, os.cpu_count())``` to ```len(collector)``` doesn't work.
Thanks for your patience.
```
./tools/dist_test.sh \
configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
checkpoints/SOME_CHECKPOINT.pth 1 --eval mAP
```

**Comment by liuyanyi** [comment] 2022-02-20 07:55
> The command below works well but only changing `min(4, os.cpu_count())` to `len(collector)` doesn't work. Thanks for your patience.
> 
> ```
> ./tools/dist_test.sh \
> configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x_dota_le90.py \
> checkpoints/SOME_CHECKPOINT.pth 1 --eval mAP
> ```

https://github.com/open-mmlab/mmrotate/blob/6519a3654e17b707c15d4aa2c5db1257587ea4c0/mmrotate/datasets/dota.py#L240-L242

`        merged_results = mmcv.track_iter_progress(
                (map(merge_func, collector.items()), len(collector)))`

You can try this, format result works fine but eval mAP still stuck

**Comment by yangxue0827** [comment] 2022-02-20 08:01
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/29257168/154833818-8b23ad7f-44cb-4232-906d-e2496b052548.png">
PR is processing, you can try it manually first, feedback is welcome.

**Comment by Adlith** [comment] 2022-02-20 08:03
@liuyanyi @yangxue0827 @zytx121 It's very kind of you.

**Closed** 2022-02-21 03:27 UTC

**Comment by houw0517** [comment] 2022-03-04 01:33
![image](https://user-images.githubusercontent.com/86358057/156682112-519302f0-6b0f-4b94-95ab-f63175b72a39.png)
