### ISSUE TITLE
AssertionError: points_in_ploygons_forward miss in module_ext

### ISSUE THREAD

**Issue by houw0517** [open-mmlab/mmrotate#74] opened 2022-03-06 07:57 UTC
![8{NUOXN$Z%6P$ES(AVVB0KH](https://user-images.githubusercontent.com/86358057/156914377-0ba4427f-99df-418b-9db8-fd781ceb665c.png)

**Comment by zytx121** [comment] 2022-03-07 01:47
duplicate of #71

**Closed by zytx121** 2022-03-07 01:47 UTC
Labels: duplicate
